name: Deploy Hexo to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Manually clone NexT theme
        run: |
          rm -rf themes/next  # 删除旧的 NexT 主题
          git clone --depth=1 https://github.com/theme-next/hexo-theme-next.git themes/next

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ACTION_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
          npm install hexo-cli -g

      - name: Generate static files
        run: hexo generate

      - name: Manually Clone Repository
        run: git clone git@github.com:harrywu0927/haruki.github.io.git test-clone

      - name: Deploy to GitHub Pages
        run: npx hexo deploy
